### ISSUE TITLE
Struct import is missing

### ISSUE THREAD

**Issue by jbdesbas** [peter-l5/MicroPython_SCD4X#6]
Hi,

Thanks for this very convenient lib.

Seems that `import struct` is missing.
https://github.com/peter-l5/MicroPython_SCD4X/blob/67319de61aa65b35dcf72d1207cffcc1811dc94d/scd4x.py#L167

**Comment by peter-l5** [comment]
Hi @jbdesbas, thanks for raising this issue. I have amended the `scd4x.py` code to import the struct module. The `scd4x.py` code seems to load OK after the change, please let me know if you encounter any further problems.

**Comment by peter-l5** [comment]
closing issue
